package types;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;

import org.bukkit.block.structure.Mirror;

import ars.Rule;
import mode.MAdv;
import mode.MArena;
import mode.MGUN;
import mode.MHeal;
import mode.MItem;
import mode.MKagerou;
import mode.MKanna;
import mode.MKiller;
import mode.MLoboTomy;
import mode.MMirror;
import mode.MNormal;
import mode.MQb;
import mode.MRandom;
import mode.MSupply;
import mode.MTeam;
import mode.MTeamMatch;
import mode.MURF;
import mode.MZombie;
import mode.MZombieAdv;
import mode.ModeBase;
import mode.lobobuff.LoboBuffBase;
import mode.lobobuff.RB_b001;
import mode.lobobuff.RB_b002;
import mode.lobobuff.RB_b003;
import mode.lobobuff.RB_b004;
import mode.lobobuff.RB_b005;
import mode.lobobuff.RB_b006;
import mode.lobobuff.RB_b007;
import mode.lobobuff.RB_b008;
import mode.lobobuff.RB_b009;
import mode.lobobuff.RB_b010;
import mode.lobobuff.RB_b011;
import mode.lobobuff.RB_b012;
import mode.lobobuff.RB_b013;
import mode.lobobuff.RB_b014;
import mode.lobobuff.RB_b015;
import mode.lobobuff.RB_b016;
import mode.lobobuff.RB_b017;
import mode.lobobuff.RB_b018;
import mode.lobobuff.RB_b019;
import mode.lobobuff.RB_b020;
import mode.lobobuff.RB_b021;
import mode.lobobuff.RB_b022;
import mode.lobobuff.RB_b023;
import mode.lobobuff.RB_b024;
import mode.lobobuff.RB_b025;
import mode.lobobuff.RB_b026;
import mode.lobobuff.RB_b027;
import mode.lobobuff.RB_b028;
import mode.lobobuff.RB_b029;
import mode.lobobuff.RB_b030;
import mode.lobobuff.RB_b031;
import mode.lobobuff.RB_b032;
import mode.lobobuff.RB_b033;
import mode.lobobuff.RB_b034;
import mode.lobobuff.RB_b035;
import mode.lobobuff.RB_b036;
import mode.lobobuff.RB_b037;
import mode.lobobuff.RB_b038;
import mode.lobobuff.RB_b039;
import mode.lobobuff.RB_b040;
import mode.lobobuff.RB_b041;
import mode.lobobuff.RB_b042;
import mode.lobobuff.RB_b043;
import mode.lobobuff.RB_b044;
import mode.lobobuff.RB_b045;
import mode.lobobuff.RB_b046;
import mode.lobobuff.RB_b047;
import mode.lobobuff.RB_b048;
import mode.lobobuff.RB_b049;
import mode.lobobuff.RB_b050;
import mode.lobobuff.RB_b051;
import mode.lobobuff.RB_b052;
import mode.lobobuff.RB_b053;
import mode.lobobuff.RB_b054;
import mode.lobobuff.RB_b055;
import mode.lobobuff.RB_b101;
import mode.lobobuff.RB_b102;
import mode.lobobuff.RB_b103;
import mode.lobobuff.RB_b104;
import mode.lobobuff.RB_b105;
import mode.lobobuff.RB_b106;
import mode.lobobuff.RB_b107;
import mode.lobobuff.RB_b110;
import mode.lobodebuff.RB_db001;
import mode.lobodebuff.RB_db002;
import mode.lobodebuff.RB_db003;
import mode.lobodebuff.RB_db004;
import mode.lobodebuff.RB_db005;
import mode.lobodebuff.RB_db006;
import mode.lobodebuff.RB_db007;
import mode.lobodebuff.RB_db008;
import mode.lobodebuff.RB_db009;
import mode.lobodebuff.RB_db010;
import mode.lobodebuff.RB_db011;
import mode.lobodebuff.RB_db012;
import mode.lobodebuff.RB_db013;
import mode.lobodebuff.RB_db014;
import mode.lobodebuff.RB_db015;
import mode.lobodebuff.RB_db016;
import mode.lobodebuff.RB_db017;
import mode.lobodebuff.RB_db018;
import mode.lobodebuff.RB_db019;
import mode.lobodebuff.RB_db020;
import mode.lobodebuff.RB_db021;
import mode.lobodebuff.RB_db022;
import mode.lobodebuff.RB_db023;
import mode.lobodebuff.RB_db024;
import mode.lobodebuff.RB_db025;
import mode.lobodebuff.RB_db026;
import mode.lobodebuff.RB_db027;
import mode.lobodebuff.RB_db028;
import mode.lobodebuff.RB_db029;
import mode.lobodebuff.RB_db030;
import mode.lobodebuff.RB_db031;
import mode.lobodebuff.RB_db032;
import mode.lobodebuff.RB_db033;
import mode.lobodebuff.RB_db034;
import mode.lobodebuff.RB_db035;
import mode.lobodebuff.RB_db036;
import mode.lobodebuff.RB_db037;
import mode.lobodebuff.RB_db101;
import util.Text;

public class LoboBuffs {
	public static LoboBuffBase get(String s) {
		if(s.equals("b1")) return new RB_b001();
		if(s.equals("b2")) return new RB_b002();
		if(s.equals("b3")) return new RB_b003();
		if(s.equals("b4")) return new RB_b004();
		if(s.equals("b5")) return new RB_b005();
		if(s.equals("b6")) return new RB_b006();
		if(s.equals("b7")) return new RB_b007();
		if(s.equals("b8")) return new RB_b008();
		if(s.equals("b9")) return new RB_b009();
		if(s.equals("b10")) return new RB_b010();
		if(s.equals("b11")) return new RB_b011();
		if(s.equals("b12")) return new RB_b012();
		if(s.equals("b13")) return new RB_b013();
		if(s.equals("b14")) return new RB_b014();
		if(s.equals("b15")) return new RB_b015();
		if(s.equals("b16")) return new RB_b016();
		if(s.equals("b17")) return new RB_b017();
		if(s.equals("b18")) return new RB_b018();
		if(s.equals("b19")) return new RB_b019();
		if(s.equals("b20")) return new RB_b020();
		if(s.equals("b21")) return new RB_b021();
		if(s.equals("b22")) return new RB_b022();
		if(s.equals("b23")) return new RB_b023();
		if(s.equals("b24")) return new RB_b024();
		if(s.equals("b25")) return new RB_b025();
		if(s.equals("b26")) return new RB_b026();
		if(s.equals("b27")) return new RB_b027();
		if(s.equals("b28")) return new RB_b028();
		if(s.equals("b29")) return new RB_b029();
		if(s.equals("b30")) return new RB_b030();
		if(s.equals("b31")) return new RB_b031();
		if(s.equals("b32")) return new RB_b032();
		if(s.equals("b33")) return new RB_b033();
		if(s.equals("b34")) return new RB_b034();
		if(s.equals("b35")) return new RB_b035();
		if(s.equals("b36")) return new RB_b036();
		if(s.equals("b37")) return new RB_b037();
		if(s.equals("b38")) return new RB_b038();
		if(s.equals("b39")) return new RB_b039();
		if(s.equals("b40")) return new RB_b040();
		if(s.equals("b41")) return new RB_b041();
		if(s.equals("b42")) return new RB_b042();
		if(s.equals("b43")) return new RB_b043();
		if(s.equals("b44")) return new RB_b044();
		if(s.equals("b45")) return new RB_b045();
		if(s.equals("b46")) return new RB_b046();
		if(s.equals("b47")) return new RB_b047();
		if(s.equals("b48")) return new RB_b048();
		if(s.equals("b49")) return new RB_b049();
		if(s.equals("b50")) return new RB_b050();
		if(s.equals("b51")) return new RB_b051();
		if(s.equals("b52")) return new RB_b052();
		if(s.equals("b53")) return new RB_b053();
		if(s.equals("b54")) return new RB_b054();
		if(s.equals("b55")) return new RB_b055();
		
		if(s.equals("o1")) return new RB_db001();
		if(s.equals("o2")) return new RB_db002();
		if(s.equals("o3")) return new RB_db003();
		if(s.equals("o4")) return new RB_db004();
		if(s.equals("o5")) return new RB_db005();
		if(s.equals("o6")) return new RB_db006();
		if(s.equals("o7")) return new RB_db007();
		if(s.equals("o8")) return new RB_db008();
		if(s.equals("o9")) return new RB_db009();
		if(s.equals("o10")) return new RB_db010();
		if(s.equals("o11")) return new RB_db011();
		if(s.equals("o12")) return new RB_db012();
		if(s.equals("o13")) return new RB_db013();
		if(s.equals("o14")) return new RB_db014();
		if(s.equals("o15")) return new RB_db015();
		if(s.equals("o16")) return new RB_db016();
		if(s.equals("o17")) return new RB_db017();
		if(s.equals("o18")) return new RB_db018();
		if(s.equals("o19")) return new RB_db019();
		if(s.equals("o20")) return new RB_db020();
		if(s.equals("o21")) return new RB_db021();
		if(s.equals("o22")) return new RB_db022();
		if(s.equals("o23")) return new RB_db023();
		if(s.equals("o24")) return new RB_db024();
		if(s.equals("o25")) return new RB_db025();
		if(s.equals("o26")) return new RB_db026();
		if(s.equals("o27")) return new RB_db027();
		if(s.equals("o28")) return new RB_db028();
		if(s.equals("o29")) return new RB_db029();
		if(s.equals("o30")) return new RB_db030();
		if(s.equals("o31")) return new RB_db031();
		if(s.equals("o32")) return new RB_db032();
		if(s.equals("o33")) return new RB_db033();
		if(s.equals("o34")) return new RB_db034();
		if(s.equals("o35")) return new RB_db035();
		if(s.equals("o36")) return new RB_db036();
		if(s.equals("o37")) return new RB_db037();
		

		if(s.equals("b101")) return new RB_b101();
		if(s.equals("b102")) return new RB_b102();
		if(s.equals("b103")) return new RB_b103();
		if(s.equals("b104")) return new RB_b104();
		if(s.equals("b105")) return new RB_b105();
		if(s.equals("b106")) return new RB_b106();
		if(s.equals("b107")) return new RB_b107();
		if(s.equals("b110")) return new RB_b110();
		if(s.equals("o101")) return new RB_db101();
		return new LoboBuffBase();
	}
	
	static public String getName(String id) {
		return Text.get("lobo:lv"+Text.getI("lobo:"+id+"v"))+ Text.get("lobo:"+id);
	}
}